/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author katja
 */
import java.text.SimpleDateFormat;
import java.util.Calendar;
public class TimeSheet extends javax.swing.JPanel {
    
    private TimeData td;
    private int weeknro;
    private DBAccess dba;
    private Account acc;
    
    /**
     * Creates new form TimeSheet
     */
    public TimeSheet(DBAccess d, Account a) {
        dba = d;
        acc = a;
        initComponents();
        td = new TimeData(dba, acc.getUserId());
        weeknro = 1;
        getTimeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        weekComboBox = new javax.swing.JComboBox();
        monField = new javax.swing.JTextField();
        tueField = new javax.swing.JTextField();
        wedField = new javax.swing.JTextField();
        thuField = new javax.swing.JTextField();
        friField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Week:");

        weekComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52" }));
        weekComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekComboBoxActionPerformed(evt);
            }
        });

        monField.setColumns(3);
        monField.setText("0");

        tueField.setColumns(3);
        tueField.setText("0");

        wedField.setColumns(3);
        wedField.setText("0");

        thuField.setColumns(3);
        thuField.setText("0");

        friField.setColumns(3);
        friField.setText("0");

        jLabel2.setText("Mon");

        jLabel3.setText("Tue");

        jLabel4.setText("Wed");

        jLabel5.setText("Thu");

        jLabel6.setText("Fri");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(weekComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(monField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tueField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(wedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(thuField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(friField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(jButton1)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(weekComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(monField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tueField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(wedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(thuField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(friField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jButton1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.WEEK_OF_YEAR, weeknro);
        double hours = 0;
        
        hours = Double.parseDouble(monField.getText());
        if(hours>=0){
            cal.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
            td.setDate(sdf.format(cal.getTime()));
            td.setHours(hours);
            td.setCoeff(1);
            td.saveTimeData();
        }
        
        hours = Double.parseDouble(tueField.getText());
        if(hours>=0){
            cal.set(Calendar.DAY_OF_WEEK, Calendar.TUESDAY);
            td.setDate(sdf.format(cal.getTime()));
            td.setHours(hours);
            td.setCoeff(1);
            td.saveTimeData();
        }
        
        hours = Double.parseDouble(wedField.getText());
        if(hours>=0){
            cal.set(Calendar.DAY_OF_WEEK, Calendar.WEDNESDAY);
            td.setDate(sdf.format(cal.getTime()));
            td.setHours(hours);
            td.setCoeff(1);
            td.saveTimeData();
        }
        
        hours = Double.parseDouble(thuField.getText());
        if(hours>=0){
            cal.set(Calendar.DAY_OF_WEEK, Calendar.THURSDAY);
            td.setDate(sdf.format(cal.getTime()));
            td.setHours(hours);
            td.setCoeff(1);
            td.saveTimeData();
        }
        
        hours = Double.parseDouble(friField.getText());
        if(hours>=0){
            cal.set(Calendar.DAY_OF_WEEK, Calendar.FRIDAY);
            td.setDate(sdf.format(cal.getTime()));
            td.setHours(hours);
            td.setCoeff(1);
            td.saveTimeData();
        }
        
        getTimeData();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void weekComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekComboBoxActionPerformed
        // TODO add your handling code here:
        weeknro = weekComboBox.getSelectedIndex()+1;
        getTimeData();        
    }//GEN-LAST:event_weekComboBoxActionPerformed
    
    private void getTimeData(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.WEEK_OF_YEAR, weeknro);        
        
        cal.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        td.setDate(sdf.format(cal.getTime()));
        td.loadTimeData();
        monField.setText(Double.toString(td.getHours()));
        
        cal.set(Calendar.DAY_OF_WEEK, Calendar.TUESDAY);
        td.setDate(sdf.format(cal.getTime()));
        td.loadTimeData();
        tueField.setText(Double.toString(td.getHours()));
        
        cal.set(Calendar.DAY_OF_WEEK, Calendar.WEDNESDAY);
        td.setDate(sdf.format(cal.getTime()));
        td.loadTimeData();
        wedField.setText(Double.toString(td.getHours()));
        
        cal.set(Calendar.DAY_OF_WEEK, Calendar.THURSDAY);
        td.setDate(sdf.format(cal.getTime()));
        td.loadTimeData();
        thuField.setText(Double.toString(td.getHours()));
        
        cal.set(Calendar.DAY_OF_WEEK, Calendar.FRIDAY);
        td.setDate(sdf.format(cal.getTime()));
        td.loadTimeData();
        friField.setText(Double.toString(td.getHours()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField friField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField monField;
    private javax.swing.JTextField thuField;
    private javax.swing.JTextField tueField;
    private javax.swing.JTextField wedField;
    private javax.swing.JComboBox weekComboBox;
    // End of variables declaration//GEN-END:variables
}
